// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Catalog struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	ParendID string `json:"parendId"`
}

type Item struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Instock   int    `json:"instock"`
	SellerID  string `json:"sellerId"`
	CatalogID string `json:"catalogId"`
}

type Query struct {
}

type Seller struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Deals string `json:"deals"`
}
