// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Child struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Item struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	InStock   int    `json:"inStock"`
	SellerID  string `json:"sellerId"`
	CatalogID string `json:"catalogId"`
}

type Query struct {
}

type Seller struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Deals string `json:"deals"`
}
