package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"shopql/graph/model"
	"strconv"
)

// Childs is the resolver for the childs field.
func (r *catalogResolver) Childs(ctx context.Context, obj *model.Catalog) ([]*model.Child, error) {
	res := make([]*model.Child, 0)
	for _, c := range r.Resolver.Data.Catalog {
		if c.ParendID == obj.ID {
			child := &model.Child{
				ID:   c.ID,
				Name: c.Name,
			}
			res = append(res, child)
		}
	}
	return res, nil
}

// Items is the resolver for the items field.
func (r *catalogResolver) Items(ctx context.Context, obj *model.Catalog) ([]*model.Item, error) {
	var cnt int
	res := make([]*model.Item, 0)
	for _, itm := range r.Resolver.Data.Item {
		if itm.CatalogID == obj.ID {
			item := itm
			res = append(res, &item)
			cnt++
		}
		if cnt == 3 { // по умолчанию максимум 3 жлемента
			break
		}
	}
	return res, nil
}

// Catalog is the resolver for the Catalog field.
func (r *queryResolver) Catalog(ctx context.Context, id string) (*model.Catalog, error) {
	fmt.Println(r.Resolver.Data.Catalog)
	idInt, _ := strconv.Atoi(id)
	for _, catalog := range r.Resolver.Data.Catalog {
		if catalog.ID == idInt {
			return &catalog, nil
		}
	}
	return nil, fmt.Errorf("Каталог с ID=%s не найден", id)
}

// Catalog returns CatalogResolver implementation.
func (r *Resolver) Catalog() CatalogResolver { return &catalogResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type catalogResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
type mutationResolver struct{ *Resolver }
